name: 🧰 Pull Request CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '**/*.md'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_API_VERSION: 1.43
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...